# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_category'),
        ('categories', '0002_auto_20170327_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
