# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170327_2218'),
        ('products', '0003_auto_20170327_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
